server:
  port: 7002
  servlet:
    contextPath: /api

spring:
  application:
    name: fee-service
  cache:
    type: simple
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  config:
    import: optional:file:.env.${spring.profiles.active}[.properties]
