drools:
  fee-cal:
    drl-path: ${DRL_PATH}
    variables:
      globals:
        flag-name: ${FEE_CALC_FLAG_VARIABLE_NAME}

mqtt:
  connection:
    string: ${MQTT_CONNECTION_STRING:tcp://localhost:18014}
  clientId: bidv-fee-calc
